fixes for linux ci

diff --git a/.azure-pipelines/Linux-CI.yml b/.azure-pipelines/Linux-CI.yml
--- a/.azure-pipelines/Linux-CI.yml
+++ b/.azure-pipelines/Linux-CI.yml
@@ -40,31 +40,60 @@ jobs:
       packageSpecs: 'python=$(python.version) protobuf'
 
   - script: |
-      python -m pip install --upgrade pip
-      python -m pip install --quiet -U dos2unix
+      python -m pip install --upgrade pip      
       python -m pip install numpy
       git submodule update --init --recursive
-      set ONNX_ML=${onnx_ml}
-      set DEBUG=${onnx_debug}
-      set ONNX_BUILD_TESTS=1
-      set USE_MSVC_STATIC_RUNTIME=0
-      set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON
-      python setup.py --quiet install
+      export ONNX_ML=${onnx_ml}
+      export DEBUG=${onnx_debug}
+      export ONNX_BUILD_TESTS=1
+      export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
+      export CMAKE_ARGS="-DONNX_WERROR=ON -DONNXIFI_DUMMY_BACKEND=ON -DONNX_USE_LITE_PROTO=ON"
+      python setup.py --quiet bdist_wheel --universal --dist-dir .
+      find . -maxdepth 1 -name "*.whl" -ls -exec pip install {} \;
     displayName: 'Install ONNX and dependencies'
 
 
   - script: |
-      pip install --quiet pytest nbval flake8
-      pytest
+      # lint python code
+      pip install --quiet flake8
       flake8
+      if [ $? -ne 0 ]; then
+        echo "Flake8 returned failures"
+        exit 1
+      fi
+
+      # check line endings to be UNIX
+      python -m pip install --quiet -U dos2unix
       find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
       git status
       git diff --exit-code
+      
+      # check auto-gen files up-to-date
       python onnx/defs/gen_doc.py
       python onnx/gen_proto.py -l
       python onnx/gen_proto.py -l --ml
       python onnx/backend/test/stat_coverage.py
       backend-test-tools generate-data
       git status
-      git diff --exit-code
+      git diff --exit-code      
+
+      # Do not hardcode onnx's namespace in the c++ source code, so that
+      # other libraries who statically link with onnx can hide onnx symbols
+      # in a private namespace.
+      ! grep -R --include='*.cc' --include='*.h' 'namespace onnx' .
+      ! grep -R --include='*.cc' --include='*.h' 'onnx::' .
+
+      # onnx python api tests
+      pip install --quiet pytest nbval
+      pytest
+      if [ $? -ne 0 ]; then
+        echo "pytest failed"
+        exit 1
+      fi
+
+      # onnx c++ API tests
+      # do not use find -exec here, it would ignore the segement fault of gtest.
+      ./.setuptools-cmake-build/onnx_gtests
+      ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
+
     displayName: 'Run ONNX tests'
