Update Linux-CI.yml for Azure Pipelines

diff --git a/.azure-pipelines/Linux-CI.yml b/.azure-pipelines/Linux-CI.yml
--- a/.azure-pipelines/Linux-CI.yml
+++ b/.azure-pipelines/Linux-CI.yml
@@ -47,18 +47,19 @@ jobs:
       export ONNX_ML=${onnx_ml}
       export DEBUG=${onnx_debug}
       export ONNX_BUILD_TESTS=1
-      export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNXIFI_DUMMY_BACKEND=ON"
+      export CMAKE_ARGS="-DONNX_WERROR=ON -DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNXIFI_DUMMY_BACKEND=ON"
       export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
       python setup.py --quiet install
     displayName: 'Install ONNX and dependencies'
 
 
   - script: |
+      @echo ON
       # lint python code
       pip install --quiet flake8
       flake8
       if [ $? -ne 0 ]; then
-        echo "Flake8 returned failures"
+        echo "flake8 returned failures"
         exit 1
       fi
 
@@ -91,15 +92,18 @@ jobs:
       fi
 
       # onnx c++ API tests
-      #export LD_LIBRARY_PATH="./.setuptools-cmake-build/:$LD_LIBRARY_PATH"
-      # do not use find -exec here, it would ignore the segement fault of gtest.
+      export LD_LIBRARY_PATH="./.setuptools-cmake-build/:$LD_LIBRARY_PATH"
       ./.setuptools-cmake-build/onnx_gtests
       if [ $? -ne 0 ]; then
-        echo "pytest failed"
+        echo "onnx_gtests failed"
         exit 1
       fi
 
       ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
+      if [ $? -ne 0 ]; then
+        echo "onnxifi_test_driver_gtests failed"
+        exit 1
+      fi
 
       # Mypy only works with Python 3
       if [ "${python.version}" != "2.7" ]; then
