Update Linux-CI.yml for Azure Pipelines

diff --git a/.azure-pipelines/Linux-CI.yml b/.azure-pipelines/Linux-CI.yml
--- a/.azure-pipelines/Linux-CI.yml
+++ b/.azure-pipelines/Linux-CI.yml
@@ -11,50 +11,56 @@ jobs:
         python.version: '2.7'
         onnx_ml: 0
         onnx_debug: 0
+        onnx_lite: 1
       py36:
         python.version: '3.6'
         onnx_ml: 0
         onnx_debug: 0
+        onnx_lite: 1
+      py36-ml:
+        python.version: '3.6'
+        onnx_ml: 1
+        onnx_debug: 0
+        onnx_lite: 1
       py37:
         python.version: '3.7'
         onnx_ml: 0
         onnx_debug: 0
+        onnx_lite: 1
       py37-ml:
         python.version: '3.7'
         onnx_ml: 1
         onnx_debug: 0
+        onnx_lite: 1
       py37-ml-debug:
         python.version: '3.7'
         onnx_ml: 1
         onnx_debug: 1
-    maxParallel: 5
+        onnx_lite: 0
+    maxParallel: 6
 
   steps:
-  - script: sudo install -d -m 0777 /home/vsts/.conda/envs
-    displayName: Fix Conda permissions
-
-  - task: CondaEnvironment@1
-    inputs:
-      createCustomEnvironment: true
-      environmentName: 'py$(python.version)'
-      packageSpecs: 'python=$(python.version) protobuf'
-
   - script: |
       python -m pip install --upgrade pip
       sudo apt-get install -qq -o=Dpkg::Use-Pty=0 -y --no-install-recommends dos2unix
+      sudo apt-get install -y --no-install-recommends protobuf-compiler libprotoc-dev
       python -m pip install numpy
       git submodule update --init --recursive
-      export ONNX_ML=${onnx_ml}
-      export DEBUG=${onnx_debug}
       export ONNX_BUILD_TESTS=1
-      export CMAKE_ARGS="-DONNXIFI_DUMMY_BACKEND=ON"
+      if [ '$(onnx_debug)' == '1' ]; then
+        export DEBUG=1
+      fi
+      if [ '$(onnx_ml)' == '1' ]; then
+        export ONNX_ML=1
+      fi
+      export CMAKE_ARGS="-DONNXIFI_DUMMY_BACKEND=ON -DONNX_WERROR=ON"
+      if [ '$(onnx_lite)' == '1' ]; then
+        export CMAKE_ARGS="${CMAKE_ARGS} -DONNX_USE_LITE_PROTO=ON"
+      fi
       export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
       python setup.py --quiet install
     displayName: 'Install ONNX and dependencies'
-
-
   - script: |
-      @echo ON
       # lint python code
       pip install --quiet flake8
       flake8
@@ -62,12 +68,14 @@ jobs:
         echo "flake8 returned failures"
         exit 1
       fi
-
       # check line endings to be UNIX
       find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
       git status
       git diff --exit-code
-      
+      if [ $? -ne 0 ]; then
+        echo "Line ending check failed. All line endings should be unix style."
+        exit 1
+      fi
       # check auto-gen files up-to-date
       python onnx/defs/gen_doc.py
       python onnx/gen_proto.py -l
@@ -75,14 +83,16 @@ jobs:
       python onnx/backend/test/stat_coverage.py
       backend-test-tools generate-data
       git status
-      git diff --exit-code
-
+      git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
+      if [ $? -ne 0 ]; then
+        echo "git diff returned failures"
+        exit 1
+      fi
       # Do not hardcode onnx's namespace in the c++ source code, so that
       # other libraries who statically link with onnx can hide onnx symbols
       # in a private namespace.
       ! grep -R --include='*.cc' --include='*.h' 'namespace onnx' .
       ! grep -R --include='*.cc' --include='*.h' 'onnx::' .
-
       # onnx python api tests
       if [ "$(python.version)" == "2.7" ]; then
         pip install --quiet pytest nbval
@@ -96,7 +106,6 @@ jobs:
         echo "pytest failed"
         exit 1
       fi
-
       # onnx c++ API tests
       export LD_LIBRARY_PATH="./.setuptools-cmake-build/:$LD_LIBRARY_PATH"
       ./.setuptools-cmake-build/onnx_gtests
@@ -104,22 +113,23 @@ jobs:
         echo "onnx_gtests failed"
         exit 1
       fi
-
       ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
       if [ $? -ne 0 ]; then
         echo "onnxifi_test_driver_gtests failed"
         exit 1
       fi
-
       # Mypy only works with Python 3
       if [ "$(python.version)" != "2.7" ]; then
         # Mypy only works with our generated _pb.py files when we install in develop mode, so let's do that
         pip uninstall -y onnx
         ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI pip install --no-use-pep517 -e .[mypy]
         python setup.py --quiet typecheck
+        if [ $? -ne 0 ]; then
+          echo "type check failed"
+          exit 1
+        fi
         pip uninstall -y onnx
         rm -rf .setuptools-cmake-build
         ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI pip install .
       fi
-
     displayName: 'Run ONNX tests'
