Update Linux-CI.yml for Azure Pipelines

diff --git a/.azure-pipelines/Linux-CI.yml b/.azure-pipelines/Linux-CI.yml
--- a/.azure-pipelines/Linux-CI.yml
+++ b/.azure-pipelines/Linux-CI.yml
@@ -63,7 +63,6 @@ jobs:
       fi
 
       # check line endings to be UNIX
-      sudo apt-get install -y --no-install-recommends dos2unix
       find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
       git status
       git diff --exit-code
@@ -92,13 +91,18 @@ jobs:
       fi
 
       # onnx c++ API tests
-      export LD_LIBRARY_PATH="./.setuptools-cmake-build/:$LD_LIBRARY_PATH"
+      #export LD_LIBRARY_PATH="./.setuptools-cmake-build/:$LD_LIBRARY_PATH"
       # do not use find -exec here, it would ignore the segement fault of gtest.
       ./.setuptools-cmake-build/onnx_gtests
+      if [ $? -ne 0 ]; then
+        echo "pytest failed"
+        exit 1
+      fi
+
       ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
 
       # Mypy only works with Python 3
-      if [ "${PYTHON_VERSION}" != "python2" ]; then
+      if [ "${python.version}" != "2.7" ]; then
         # Mypy only works with our generated _pb.py files when we install in develop mode, so let's do that
         pip uninstall -y onnx
         ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI pip install --no-use-pep517 -e .[mypy]
